module.exports = {
  compterendu: [
    {
      type: "type 1",
      atcd: "sd malformatif tube neurale",
      quality: "Bonne",
      indication: {
        situs: "",
        aorte:
          "Non delaté, libre, en place, concordance mitrtro-aortique respectée. pas de coactation.",
        valveAortique: "",
        oreilletteGauche: "Non delatée",
        sia: "petite CIA OS 3mm",
        valveMitrale: "fine, pas de fuite, pas de sténose",
        ventriculeGauche: {
          motif: "Non delaté, non hypertrophie, bonne fonction systolique",
          dtd: "",
          siv: "",
          fe: "",
        },
        siv: "pas de shunt interclaviculaire",
        cavitesDroites: "Non delaté, pas d'HTAP",
        tricuspide: "fine IT minime",
        arterePulmonaire: "Non delaté sans fuite ni sténose",
        pericarde: "SEC",
      },
      conclusion: "petite CIA OS sans retentissement",
      conduiteMedicale: "",
    },
    {
      type: "type 2",
      atcd: "",
      quality: "Bonne",
      indication: {
        situs: "Solitus",
        aorte:
          "Non delaté, libre, en place, concordance mitrtro-aortique respectée. pas de coactation.",
        valveAortique: "",
        oreilletteGauche: "Non delatée",
        sia: "Petite CIA OS 3mm",
        valveMitrale: "Fine, pas de fuite, pas de sténose",
        ventriculeGauche: {
          motif: "Non delaté, non hypertrophie, bonne fonction systolique",
          dtd: "3.2",
          siv: "4",
          fe: "80%",
        },
        siv: "pas de shunt interclaviculaire",
        cavitesDroites: "Non delaté, pas d'HTAP",
        tricuspide: "fine IT minime",
        arterePulmonaire: "Non delaté sans fuite ni sténose",
        pericarde: "SEC",
      },
      conclusion: "Examen sans anomalies",
      conduiteMedicale: "",
    },
    {
      type: "type 3",
      atcd: "Souffle cardiaque",
      quality: "Bonne",
      indication: {
        situs: "",
        aorte:
          "Non delaté, libre, en place, concordance mitrtro-aortique respectée.",
        valveAortique: "Fuite aortique I",
        oreilletteGauche: "Non delatée",
        sia: "Intact",
        valveMitrale: "fine, pas de fuite, pas de sténose",
        ventriculeGauche: {
          motif: "Non delaté, non hypertrophie, bonne fonction systolique",
          dtd: "",
          siv: "",
          fe: "",
        },
        siv: "CIV périmembranceiuse de 7 mm avec prolapsus de la valve aortique dans la CIV",
        cavitesDroites: "Sténose médio VD modérée",
        tricuspide: "fine fuite minime",
        arterePulmonaire: "PAPS normale 7mm",
        pericarde: "SEC",
      },
      conclusion: "CIV périmembraneuse et prolapsus de la valve aortique. Fermeture percutanée de la CIV",
      conduiteMedicale: "",
    },
  ],
};
